Repository robinweser/fela, pull requests merged in 2018-12, with the labels that each got.

#645 Fix theme providers not re-rendering their children
  packages/fela-bindings/package.json
  packages/fela-bindings/src/ThemeProviderFactory.js
Labels: Version: Patch

#646 Fix Provider deprecation warning
  packages/inferno-fela/src/Provider.js
  packages/inferno-fela/src/_deprecate.js
  packages/inferno-fela/src/index.js
  packages/preact-fela/src/Provider.js
  packages/preact-fela/src/_deprecate.js
  packages/preact-fela/src/index.js
  packages/react-fela/src/Provider.js
  packages/react-fela/src/_deprecate.js
  packages/react-fela/src/index.js
Labels: Scope: Bindings, Version: Patch

#647 Expose Context
  packages/inferno-fela/src/index.js
  packages/preact-fela/src/index.js
  packages/react-fela/src/index.js
Labels: Scope: Bindings, Version: Minor
