Repository robinweser/fela, pull requests merged in 2019-02, with the labels that each got.

#670 Theme-based bidi/rtl transformation
  packages/fela-plugin-bidi/README.md
  packages/fela-plugin-bidi/src/__tests__/rtl-test.js
  packages/fela-plugin-bidi/src/index.js
  packages/fela-plugin-rtl/README.md
  packages/fela-plugin-rtl/src/__tests__/rtl-test.js
  packages/fela-plugin-rtl/src/index.js
Labels: Status: Needs Review, Version: Minor

#669 pass theme with props when using useFela
  packages/react-fela/src/useFela.js
Labels: Status: Needs Review, Version: Patch

#673 [fela-plugin-rtl] Ability to set default direction
  packages/fela-plugin-bidi/README.md
  packages/fela-plugin-rtl/README.md
  packages/fela-plugin-rtl/src/__tests__/rtl-test.js
  packages/fela-plugin-rtl/src/index.js
Labels: Scope: Plugin, Version: Patch

#674 perf(useFela): optimize passing of theme & props
  packages/react-fela/src/useFela.js
Labels: Type: DX, Type: Performance, Version: Patch
