Repository robinweser/fela, pull requests merged in 2019-01, with the labels that each got.

#648 Hooks API
  benchmarks/dom-comparison/package.json
  examples/example-react-native/package.json
  examples/example-react/package.json
  examples/example-typescript/package.json
  examples/example-with-styleguidist/package.json
  packages/fela-bindings/package.json
  packages/fela-integration/package.json
  packages/fela-integration/src/jest-react-fela_react-fela/__tests__/__snapshots__/useFela-test.js.snap
  packages/fela-integration/src/jest-react-fela_react-fela/__tests__/useFela-test.js
  packages/jest-fela-bindings/package.json
  packages/react-fela/src/index.js
  packages/react-fela/src/useFela.js
  yarn.lock
Labels: Scope: Bindings, Version: Minor

#658 fix(fela-plugin-extend): don't throw on undefined items in extend array
  packages/fela-plugin-extend/src/__tests__/extend-test.js
  packages/fela-plugin-extend/src/index.js
Labels: Version: Patch

#660 Fix styling non-standard pseudo elements
  packages/fela-dom/src/dom/connection/insertRule.js
Labels: Status: Ship It, Version: Patch
